---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
spec:
  containers:
  - name: nginx1
    image: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
  - name: nginx1
    image: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
spec:
  containers:
  - name: nginx1
    image: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  containers:
  - name: producer
    image: allingeek/ch6_ipc
    command: ["./ipc", "-producer"]
  - name: consumer
    image: allingeek/ch6_ipc
    command: ["./ipc", "-consumer"]
  restartPolicy: Never
