apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.deploy.replicas }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deploy.nginx.version }}
        ports:
        - containerPort: {{ .Values.deploy.nginx.port }}